/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "list.h"
int ordered_list[10000];
int size =1;
void *
append_1_svc(int* argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	for(int i=0; i<10; i++){
		ordered_list[(size-1)+i]=*(argp+i);
		//printf("debug server app (size-1)+i=%d ordered_list=%d and *(argp+i)=%d\n",(size-1)+i,ordered_list[(size-1)+i],*(argp+i));
	}
	size+=10;
	if(size ==11){
		size-=2;
	}
	return (void *) &result;
}

int *
query_1_svc(int* argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	if(*argp>size){
		result =-1;
	}
	else{
		//printf("debug server query %d,",*argp);
		result = ordered_list[*argp];
		
	}
	return &result;
}

int *
remove_1_svc(int* argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	if(*argp>size){
		result = -1;
	}
	else{
		for(int i=*argp; i<size;i++){
			ordered_list[i] = ordered_list[i+1];
		}
		ordered_list[size] = 0;
		size-=1;
		result = 1;
	}

	return &result;
}
