/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "list.h"

bool_t
xdr_arr (XDR *xdrs, arr objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 10,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_list (XDR *xdrs, list objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
