/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LIST_H_RPCGEN
#define _LIST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef int arr[10];

typedef int list[100];

#define LIST_PROG 0x32134567
#define LIST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define append 1
extern  void * append_1(int *, CLIENT *);
extern  void * append_1_svc(int *, struct svc_req *);
#define query 2
extern  void * query_1(int *, CLIENT *);
extern  void * query_1_svc(int *, struct svc_req *);
#define remove 3
extern  void * remove_1(int *, CLIENT *);
extern  void * remove_1_svc(int *, struct svc_req *);
#define sort 4
extern  void * sort_1(array *, CLIENT *);
extern  void * sort_1_svc(array *, struct svc_req *);
extern int list_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define append 1
extern  void * append_1();
extern  void * append_1_svc();
#define query 2
extern  void * query_1();
extern  void * query_1_svc();
#define remove 3
extern  void * remove_1();
extern  void * remove_1_svc();
#define sort 4
extern  void * sort_1();
extern  void * sort_1_svc();
extern int list_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arr (XDR *, arr);
extern  bool_t xdr_list (XDR *, list);

#else /* K&R C */
extern bool_t xdr_arr ();
extern bool_t xdr_list ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LIST_H_RPCGEN */
